In [1]:
import numpy as np

In [5]:
data_1d = np.array([1,2,3,4,5])
data_2d = np.array([[1,2,3],[4,5,6]])

In [6]:
print(data_1d.shape)

(5,)


In [7]:
print(data_2d)

[[1 2 3]
 [4 5 6]]


In [8]:
print(data_2d.shape)

(2, 3)


In [12]:
reshape_arr = data_2d.reshape(1,6)

In [13]:
reshape_arr

array([[1, 2, 3, 4, 5, 6]])

In [14]:
data_2d.ndim

2

In [15]:
reshape_arr.ndim

2