In [10]:
import numpy as np

In [11]:
data_1d = np.array([1,2,3,4,5])
data_2d = np.array([[1,2,3,4,5],[4,5,6,7,8]])

In [12]:
print(data_1d.shape)

(5,)


In [13]:
print(data_2d)

[[1 2 3 4 5]
 [4 5 6 7 8]]


In [14]:
print(data_2d.shape)

(2, 5)


In [17]:
#array reshaping
reshape = data_2d.reshape(5,2)
reshape

array([[1, 2],
       [3, 4],
       [5, 4],
       [5, 6],
       [7, 8]])